# Generated by Django 3.1.6 on 2021-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referredBby',
        ),
        migrations.AddField(
            model_name='user',
            name='referredBy',
            field=models.ManyToManyField(related_name='_user_referredBy_+', to='HarmonicProfit.User'),
        ),
    ]
