# Generated by Django 3.1.6 on 2021-02-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0002_auto_20210226_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referredBy',
        ),
        migrations.AddField(
            model_name='user',
            name='referredBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.user'),
            preserve_default=False,
        ),
    ]
