# Generated by Django 3.1.6 on 2021-02-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0006_auto_20210226_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsorship_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.sponsorshipstatus'),
        ),
    ]
