# Generated by Django 3.1.6 on 2021-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0007_auto_20210226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountStatus',
            field=models.BooleanField(default=0),
        ),
    ]
