# Generated by Django 3.1.6 on 2021-02-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0008_auto_20210226_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referredBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.user'),
        ),
    ]
