# Generated by Django 3.1.6 on 2021-03-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0009_auto_20210226_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.user'),
        ),
    ]
