# Generated by Django 3.1.6 on 2021-03-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0010_auto_20210310_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField()),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.paymentmethod')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HarmonicProfit.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
