# Generated by Django 3.1.6 on 2021-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0011_auto_20210317_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedeposit',
            name='paymentMethod',
            field=models.CharField(max_length=32),
        ),
    ]
