# Generated by Django 3.1.6 on 2021-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0013_autopool1_autopool10_autopool2_autopool3_autopool4_autopool5_autopool6_autopool7_autopool8_autopool9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsorship_status',
            field=models.CharField(default='SILVER PARTNER', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SponsorshipStatus',
        ),
    ]
