# Generated by Django 3.1.6 on 2021-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0014_auto_20210319_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sponsorship_status',
            new_name='accountType',
        ),
        migrations.AddField(
            model_name='user',
            name='sponsorshipStatus',
            field=models.CharField(default='SILVER', max_length=32),
            preserve_default=False,
        ),
    ]
