# Generated by Django 3.1.6 on 2021-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0015_auto_20210319_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountType',
            field=models.CharField(default='PARTNER', max_length=32),
        ),
    ]
