# Generated by Django 3.1.6 on 2021-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0017_auto_20210319_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsorshipStatus',
            field=models.CharField(default='SILVER', max_length=32),
        ),
    ]
