# Generated by Django 3.1.6 on 2021-03-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0018_auto_20210319_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='title',
        ),
    ]
