# Generated by Django 3.1.6 on 2021-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0020_auto_20210322_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsorshipStatus',
            field=models.IntegerField(default=0),
        ),
    ]
