# Generated by Django 3.1.6 on 2021-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0021_auto_20210322_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ambassador',
            field=models.BooleanField(default=0),
        ),
    ]
