# Generated by Django 3.1.6 on 2021-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0022_user_ambassador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountType',
        ),
    ]
