# Generated by Django 3.1.6 on 2021-03-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0024_auto_20210324_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HarmonicProfit.user'),
        ),
    ]
