# Generated by Django 3.1.6 on 2021-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonicProfit', '0026_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='status',
        ),
    ]
